language: python

cache: pip

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y mongodb-server

install:
  - make travis-install

jobs:
  include:
    - stage: unit-test
      script:
        - make travis-unit
        - make travis-examples
        - make travis-doc
        - make travis-end
